### ISSUE TITLE
Typescript type definitions

### ISSUE THREAD

**Issue by demurgos** [substack/object-inspect#16]
Hi,
It is currently inconvenient to use your package with Typescript because it lacks a type definition file.
Since the API is very minimal (it's just a function from `any` to `string`), adding the type definitions file to this repo would make sense (it's best to keep the definitions with the code).

I'll submit a PR later today.

**Comment by demurgos** [comment]
@ljharb 
Could you comment or document this line?
https://github.com/substack/object-inspect/blob/71e24db8ad6ee3b9b381c5300b0475f2ba595a73/index.js#L12

**Comment by ljharb** [comment]
This project does not use TypeScript, and type definitions thus do not belong in this repo. The proper place to add type definitions is in the DefniitelyTyped repo.

**Comment by ljharb** [comment]
The line you refer to is extracting a Symbol from node 8+.

**Comment by demurgos** [comment]
Ok,
So it means that someone can customize the inspection with a code like the following?

```javascript
const customSymbol = new Symbol();
const foo = {};
foo[customSymbol] = () => "bar";

const objectInspect = require("object-inspect");
objectInspect.custom = customSymbol;
console.log(objectInspect(foo)); // bar
```

**Comment by ljharb** [comment]
Except that you don’t need to mutate `objectInspect` (and that has no effect), yes.

**Comment by demurgos** [comment]
I see, you're right: `.custom` is read when the module is loaded so my mutation had no effect. My problem was that I couldn't find find at which point this property was set. But now I see that it's using the one from Node's core `require("util").inspect.custom`.
I knew about `prototype.inspect` but wasn't aware of the symbol. Would it benefit to document it in the `README.md`? Since this library does not support the same options as Node's version, it isn't clear what is supported and what not.

**Comment by ljharb** [comment]
This library indeed supports exactly what node's version does, as far as the API - node's supports a `.inspect()`, but prefers the symbol in newer versions - as do we.

What differences are you aware of?

**Comment by demurgos** [comment]
Thanks for clarifying that you prefer symbols: it makes sense.

The only supported (documented) option is `depth` while Node's `inspect` has [a few more options](https://nodejs.org/api/util.html#util_util_inspect_object_options) (`showHidden`, `showProxy`, `maxArrayLength`, etc.). This why I did not assume that this library tried to get feature parity.

**Comment by ljharb** [comment]
`showProxy` can't be added because Proxy detection isn't always possible - it's just that `node` has superpowers. The other options seem reasonable, but they should be added because there's a use case, not purely for consistency.
