### ISSUE TITLE
Browser bundling regression

### ISSUE THREAD

**Issue by porsager** [substack/object-inspect#18]
Bundling object-inspect with rollup doesn't work and will throw errors because it thinks the package relies on node's `util` module.
```
var inspectCustom = require('./util.inspect')
```
and there 
```
module.exports = require('util').inspect;
```

Relevant commit where the change was made.
https://github.com/substack/object-inspect/commit/20cca7762d7e17f15b21a90793dff84acce155df

**Comment by ljharb** [comment]
That commit explicitly added a [browser entry point](https://github.com/substack/object-inspect/commit/20cca7762d7e17f15b21a90793dff84acce155df#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R52) with the "browser" field in package.json.

Does rollup not support that community standard? Browserify and webpack don't seem to have trouble with it (I tested that explicitly prior to publishing).

**Comment by ljharb** [comment]
I'm going to close this; please file an issue on rollup if it can't handle the "browser" field and link it here!

**Comment by porsager** [comment]
Sorry for the late answer @ljharb ..

Seems like there's finally a PR to add support on rollup here. https://github.com/rollup/rollup-plugin-node-resolve/pull/183
