### ISSUE TITLE
Support ES2015 Map/Set

### ISSUE THREAD

**Issue by mjackson** [substack/object-inspect#3]
Using object-inspect version 1.0.2:

```js
inspect(new Set('a')) // {}

var map = new Map()
map.set('a', 'b')
inspect(map) // {}
```

These aren't very descriptive. In babel's CLI, I get `Set { 'a' }` and `Map { 'a' => 'b' }` respectively. It would be great to get the same (or similar) using object-inspect.

**Comment by ljharb** [comment]
I'm not sure the hash rocket is the best separator, since in JS that can be confused with an arrow function, but this should definitely be supported.

**Comment by ljharb** [comment]
Do you think it would be useful to explicitly indicate the size? Like `Set (2) { 'a', 'b' }` and `Map (2) { [[2, 3], [3, 4]] }`?

**Comment by ljharb** [comment]
After clicking around in browsers, I think sticking with the hash rocket works. I'm going to go with Chrome's interpretation, but add the `size` of the collection.
