### ISSUE TITLE
Polyfilled set objects fails when using inspect

### ISSUE THREAD

**Issue by roy-codefresh** [substack/object-inspect#9]
While using babel-polyfill on IE10 and IE11. The use inspect on a Set object create a fail.

As far is looked, it's seems that isMap function does not distinguish between Set object and Map object.

I was also able to recreate it on node 0.10:

```
require('babel-polyfill');
var inspect = require('object-inspect');
inspect(new Set([1, 2, 3]));
```

**Comment by ljharb** [comment]
Does the same thing happen with https://npmjs.com/es6-shim ?

**Comment by ljharb** [comment]
Also, what version of babel-polyfill? core-js fixed a [possibly related issue](https://github.com/zloirock/core-js/issues/144) in v2.0

**Comment by roy-codefresh** [comment]
Answer to your questions:

1. This does not happens on `es6-shim`.
2. `babel-polyfill` version is `6.20.0` with `core-js@2.4.1`

**Comment by ljharb** [comment]
This is a core-js issue - filed as https://github.com/zloirock/core-js/issues/272.

**Comment by ljharb** [comment]
I've added a workaround. v2.5.0+ of core-js won't have this problem, so the workaround won't be needed.
